<h1> Soal 1: Pemahaman Tentang Model Evaluasi</h1>

Jawab pertanyaan di bawah ini dengan bahasa masing-masing?

1. Apa perbedaan antara data latih, data validasi, dan data test?
2. Bagaimana cara kita menilai performa suatu model?
3. Apa itu Confusion Matrix? Jelaskan secara lengkap!
4. Apa itu Classification Report dari sklearn?

Jawab:

1. - Data latih : data yang digunakan untuk melatih model
   - Data test : data yang digunakan untuk mengetes model, sebagai simulasi penggunaan model pada dunia nyata. Data testing tidak boleh pernah dilihat oleh model sebelumnya.
   - Data Validasi :  data yang digunakan untuk proses validasi model dan mencegah overfitting.


2. Dengan melakukan pengetestan terhadap model menggunakan data test atau data yang bukan merupakan data latih. Data test ini bisa kita peroleh dari hasil splitting menggunakan suatu metode train_test_split dari library Scikit Learn. Kemudian metode .predict() dilakukan terhadap data test dan diassign ke suatu variabel misal y_predict, selanjutnya dievaluasi menggunakan suatu metrics terhadap data (y_test, y_predict).

3. Confusion matrix digunakan untuk mengevaluasi performa model terhadap data tes yang telah diketahui nilai sebenarnya. Confusion matrix memberikan informasi perbandingan hasil klasifikasi yang dilakukan oleh model dengan hasil klasifikasi sebenarnya. Confusion matrix berbentuk tabel matriks yang menggambarkan kinerja model klasifikasi pada serangkaian data uji yang nilai sebenarnya diketahui. Terdapat 4 istilah sebagai representasi hasil proses klasifikasi pada confusion matrix. Keempat istilah tersebut adalah True Positive (TP), True Negative (TN), False Positive (FP) dan False Negative (FN).Confusion matrix dapat digunakan untuk menghitung berbagai performance metrics untuk mengukur kinerja model yang telah dibuat. Performance metrics populer yang umum dan sering digunakan adalah accuracy, precission, dan recall.

4. Classification Report digunakan untuk menampilkan report hasil perhitungan berbagai performance metrics berdasarkan hasil dari confusion matrix. Performance metrics yang ditampilkan adalah precission, recall, f1-score, dan support.


<h1>Soal 2: Aplikasi Model Evaluasi</h1>

Kali ini kita akan menggunakan data untuk memprediksi kelangsungan hidup pasien yang telah mengalami operasi payudara. Dengan informasi yang dimiliki terkait pasien, kita akan membuat model untuk memprediksi apakah pasien akan bertahan hidup dalam waktu lebih dari 5 tahun atau tidak.

Lebih Lengkapnya kalian bisa membaca informasi tentang dataset di link berikut: https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.names

Buat model Klasifikasi (Model/Algoritma Bebas) untuk memprediksi status pasien dengan ketentuan sebagai berikut:

1. Bagi kedua data ini menjadi data training dan data test dengan test_size=0.25.
3. Pelajar tentang metrics roc_auc_score kemudian buatlah model dan evaluasi dengan menggunakan teknik cross-validation dengan scoring 'roc_auc'. Baca https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.cross_val_score.html untuk menggunakan metric roc_auc saat cross-validation.
3. Berapa score rata2 dari model dengan teknik cross-validation tersebut?
4. Prediksi data test dengan model yang telah kalian buat!
5. Bagaimana hasil confusion matrix dari hasil prediksi tersebut?
6. Bagaimana classification report dari hasil prediksi tersebut?
5. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status positive?
6. Seberapa baik model anda dalam memprediksi seorang pasien mempunyai status negatif?

In [61]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [62]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [63]:
df['survival_status'].value_counts()

1    225
2     81
Name: survival_status, dtype: int64

In [64]:
X = df.drop('survival_status', axis=1)
y = df['survival_status']

In [78]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y, random_state=40)

In [79]:
model_lr = LogisticRegression()

In [80]:
score = cross_val_score(model_lr, X, y, cv=5, scoring='roc_auc')
np.mean(score)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

0.7125

In [81]:
model_lr.fit(X_train, y_train)
y_pred = model_lr.predict(X_test)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [82]:
from sklearn.metrics import confusion_matrix, classification_report
confusion_matrix(y_test, y_pred, labels=[1,2])

array([[54,  3],
       [14,  6]], dtype=int64)

In [83]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.79      0.95      0.86        57
           2       0.67      0.30      0.41        20

   micro avg       0.78      0.78      0.78        77
   macro avg       0.73      0.62      0.64        77
weighted avg       0.76      0.78      0.75        77



Jawab :

7. performa model dalam memprediksi seorang pasien mempunyai status positive adalah sebesar 79%
8. performa model dalam memprediksi seorang pasien mempunyai status negatif adalah sebesar 67%

---

<h1> Soal 3: Pemahaman Tentang Model Selection</h1>

Jelaskan dengan bahasa sendiri!

1. Apa itu Bias dan Variance?
2. Apa itu Overfitting dan Underfitting?
3. Apa yang bisa kita lakukan untuk mengatur kompleksitas dari model?
4. Bagaimana model yang baik?
5. Kapan kita menggunakan GridSearchcv dan kapan menggunakan RandomizedSearchCV?

Jawab:

1. - Bias : error yang disebabkan karena model terlalu simple
   - Variance : error yang disebabkan karena model terlalu kompleks


2. - Overfitting : Model terlalu belajar terhadap data training, sehingga terlalu menangkap detail dan noise pada data training. sehingga kemampuan generalisasi pada data test kurang.
   - Underfitting : Model terlalu jelek/ simple dalam belajar terhadap data training. 


3. Dengan melakukan tuning hyperparameter untuk mendapatkan hyperparameter terbaik yang menghasilkan training score dan test score yang tinggi

4.  Model yang baik adalah model yang memiliki error bias kecil dan error variance kecil

5. - GridSearchcv : akan mencoba semua kombinasi hyperparameter yang mungkin
   - RandomizedSearchCV : hanya akan memilih beberapa kombinasi hyperparameter secara random

---

<h1> Soal 4: Aplikasi Model Selection</h1>

1. Bagi kedua data berikut ini menjadi data training dan data test dengan test_size=0.25.
2. Gunakan algoritma KNN sebagai model classifier.
3. Gunakan fungsi GridSearchCV untuk hyperparameter tuning dan model selection.
4. jumlah fold bebas!, gunakan scoring 'roc_auc'
5. Definisikan kombinasi hyperparameter untuk model selection dengan GridSearchCV. kombinasi Hyperparameter bebas, baca lagi dokumentasi KNN di link berikut https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html untuk memahami lagi jenis2 hyperparameter di algorithma KNN.
6. Latih model terhadap data training.
7. Apa hyperparameter terbaik untuk kombinasi hyperparameter kalian?
8. Berapa score validasi terbaik dari model tersebut?
9. Prediksi probabilitasi output dari model yang telah di buat terhadap data test. note : gunakan method .predict_proba() untuk menghasilkan output probabilitas
10. Perhatikan bahwa hasil prediksi ada 2, dimana masing2 adalah nilai probabilitas untuk setiap class label. Ambil nilai probabilitas pasien phositive meninggal dalam waktu kurang dari 5 tahun. note : gunakan bantuan attirubte .classes_ untuk mengetahui urutan label dari hasil prediksi probabilitas.
11. Berapa nilai score roc_auc untuk data test?
12. Apakah model anda termasuk baik, overtting, atau underfitting?
13. Ulangi tahap di atas namun kali ini menggunakan algoritma DecisionTreeClassifier dan kalian bisa menggunakan RandomizedSearchCV apabila process training lama. pelajari algoritma DecisionTreeClassifier di linkberikut: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html?highlight=decisiontreeclassifier#sklearn.tree.DecisionTreeClassifier
14. Bandingkan scorenya dengan Algoritma KNN, mana yang lebih baik?

Note : Data Science adalah experiment, sangat di dimungkinkan memerlukan beberapa kali percobaan untuk mendapatkan hasil yang terbaik! Happy Coding :)

In [34]:
import pandas as pd

url = 'https://raw.githubusercontent.com/jbrownlee/Datasets/master/haberman.csv'
list_cols = ['Age', "Patient's Years", "N_positive_ax", "survival_status"]
df = pd.read_csv(url, names=list_cols)

In [35]:
df.head()

Age  Patient's Years  N_positive_ax  survival_status
0   30               64              1                1
1   30               62              3                1
2   30               65              0                1
3   31               59              2                1
4   31               65              4                1

In [36]:
X = df.drop('survival_status', axis=1)
y = df['survival_status']

In [87]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier as knn
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y, random_state=40)

In [90]:
model_knn = knn()
param_grid = {'n_neighbors':np.arange(5,50), 'weights':['distance','uniform']}
gscv = GridSearchCV(model_knn, param_grid = param_grid, scoring='roc_auc', cv=5)
gscv.fit(X_train, y_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), 'weights': ['distance', 'uniform']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=0)

In [92]:
gscv.best_params_

{'n_neighbors': 16, 'weights': 'uniform'}

In [93]:
gscv.best_score_

0.6537254273254787

In [111]:
y_pred_prob = gscv.predict_proba(X_test)
y_pred_prob

array([[0.6875, 0.3125],
       [0.5625, 0.4375],
       [0.625 , 0.375 ],
       [0.8125, 0.1875],
       [0.8125, 0.1875],
       [0.8125, 0.1875],
       [0.875 , 0.125 ],
       [0.875 , 0.125 ],
       [0.875 , 0.125 ],
       [0.8125, 0.1875],
       [0.875 , 0.125 ],
       [0.9375, 0.0625],
       [0.75  , 0.25  ],
       [0.75  , 0.25  ],
       [0.75  , 0.25  ],
       [0.8125, 0.1875],
       [0.4375, 0.5625],
       [0.8125, 0.1875],
       [0.4375, 0.5625],
       [0.375 , 0.625 ],
       [0.6875, 0.3125],
       [0.8125, 0.1875],
       [0.375 , 0.625 ],
       [0.8125, 0.1875],
       [1.    , 0.    ],
       [0.75  , 0.25  ],
       [0.875 , 0.125 ],
       [0.875 , 0.125 ],
       [0.75  , 0.25  ],
       [0.9375, 0.0625],
       [0.375 , 0.625 ],
       [0.8125, 0.1875],
       [0.5625, 0.4375],
       [0.6875, 0.3125],
       [0.75  , 0.25  ],
       [0.875 , 0.125 ],
       [0.75  , 0.25  ],
       [0.4375, 0.5625],
       [0.8125, 0.1875],
       [0.875 , 0.125 ],


In [104]:
gscv.classes_

array([1, 2], dtype=int64)

In [112]:
y_pred_prob_kurang5 = y_pred_prob[:,1]
y_pred_prob_kurang5

array([0.3125, 0.4375, 0.375 , 0.1875, 0.1875, 0.1875, 0.125 , 0.125 ,
       0.125 , 0.1875, 0.125 , 0.0625, 0.25  , 0.25  , 0.25  , 0.1875,
       0.5625, 0.1875, 0.5625, 0.625 , 0.3125, 0.1875, 0.625 , 0.1875,
       0.    , 0.25  , 0.125 , 0.125 , 0.25  , 0.0625, 0.625 , 0.1875,
       0.4375, 0.3125, 0.25  , 0.125 , 0.25  , 0.5625, 0.1875, 0.125 ,
       0.1875, 0.125 , 0.4375, 0.25  , 0.375 , 0.0625, 0.25  , 0.1875,
       0.1875, 0.625 , 0.3125, 0.125 , 0.125 , 0.3125, 0.1875, 0.5   ,
       0.125 , 0.3125, 0.5625, 0.1875, 0.5625, 0.125 , 0.1875, 0.5625,
       0.25  , 0.3125, 0.0625, 0.125 , 0.1875, 0.25  , 0.125 , 0.0625,
       0.1875, 0.25  , 0.125 , 0.0625, 0.125 ])

In [115]:
from sklearn.metrics import roc_auc_score

y_pred = gscv.predict(X_test)
scores_data_test = roc_auc_score(y_test, y_pred)
scores_data_test

0.6824561403508772

In [116]:
y_train_pred = gscv.predict(X_train)
scores_data_train = roc_auc_score(y_train, y_train_pred)
scores_data_train

0.5305913348946135

Jawab :
Model termasuk cukup baik karena nilai scores data train dan data test tinggi dan tidak terlalu berjauhan.

### DecisionTreeClassifier

In [125]:
from sklearn.tree import DecisionTreeClassifier as dtc

model_dtc = dtc()
param_grid = {'min_samples_split': np.arange(5,50), 'min_samples_leaf':np.arange(1,10)}

gscv_dtc = GridSearchCV(model_dtc, param_grid = param_grid, scoring='roc_auc', cv=5)
gscv_dtc.fit(X_train, y_train) 

C:\Users\ASUS\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'min_samples_split': array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]), 'min_samples_leaf': array([1, 2, 3, 4, 5, 6, 7, 8, 9])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='roc_auc', verbose=0)

In [126]:
gscv_dtc.best_params_

{'min_samples_leaf': 2, 'min_samples_split': 15}

In [127]:
gscv_dtc.best_score_

0.6499240014202768

In [133]:
y_pred_prob = gscv_dtc.predict_proba(X_test)
y_pred_prob

array([[1.        , 0.        ],
       [0.16666667, 0.83333333],
       [0.55555556, 0.44444444],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.5       , 0.5       ],
       [0.6       , 0.4       ],
       [0.66666667, 0.33333333],
       [1.        , 0.        ],
       [0.        , 1.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.25      , 0.75      ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [1.        , 0.        ],
       [0.33333333, 0.66666667],
       [1.        , 0.        ],
       [0.16666667, 0.83333333],
       [0.85714286, 0.14285714],
       [1.        , 0.        ],
       [0.63636364, 0.36363636],
       [1.        , 0.        ],
       [0.

In [134]:
y_pred_prob_kurang5 = y_pred_prob[:,1]
y_pred_prob_kurang5

array([0.        , 0.83333333, 0.44444444, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.5       , 0.4       , 0.33333333,
       0.        , 1.        , 0.        , 0.        , 0.75      ,
       0.        , 0.        , 0.        , 0.66666667, 0.        ,
       0.83333333, 0.14285714, 0.        , 0.36363636, 0.        ,
       1.        , 0.5       , 1.        , 0.4       , 0.44444444,
       0.        , 0.77777778, 0.16666667, 0.83333333, 0.14285714,
       0.36363636, 0.        , 0.16666667, 0.36363636, 0.44444444,
       0.        , 0.        , 0.14285714, 0.        , 0.14285714,
       0.77777778, 0.        , 0.        , 0.14285714, 0.66666667,
       0.75      , 0.16666667, 0.4       , 0.4       , 0.33333333,
       0.75      , 0.        , 0.        , 0.16666667, 0.25      ,
       0.41666667, 0.        , 0.        , 0.33333333, 0.        ,
       0.        , 0.33333333, 0.        , 0.        , 0.     

In [135]:
from sklearn.metrics import roc_auc_score

y_pred = gscv_dtc.predict(X_test)
scores_data_test = roc_auc_score(y_test, y_pred)
scores_data_test

0.5548245614035088

In [136]:
y_train_pred = gscv_dtc.predict(X_train)
scores_data_train = roc_auc_score(y_train, y_train_pred)
scores_data_train

0.7384855581576893

Jika dibandingkan dengan algoritma KNN maka model KNN lebih baik dibanding model DecisionTree, karena nilai score data test model KNN lebih tinggi. Dan jika dilihat dari nilai score data test dan data train pada model Decision Tree maka dapat dikatakan bahwa model mengalami overfitting, karena score data trainingnya tinggi sedangkan score data testnya rendah